### ISSUE TITLE
BetaBuilder doesn't compile out-of-the-box

### ISSUE THREAD

**Issue by ycrausaz** [HunterHillegas/iOS-BetaBuilder#5]
Hello,

I'm not an expert in Obj-C, but I had to make some little changes to have BetaBuilder (version 1.6.3 (6)) compile:
- removed the file 'BetaBuilder.icns' from the 'Resources' group in Xcode;
- had to add the following declaration before "@interface BuilderController : NSObject <NSFileManagerDelegate> {" in the file 'BuilderController.h': 

@protocol NSFileManagerDelegate <NSObject>
@end

Maybe it's just a silly remark, but maybe it could help someone else...
Best regards,
Y

**Comment by pavankataria** [comment]
And how would this compile with El Capitan?
